- pipeline.id: initialization-pipeline
  path.config: "/usr/share/logstash/pipeline/initialization.conf"

- pipeline.id: incremental-pipeline
  path.config: "/usr/share/logstash/pipeline/incremental.conf"